site_name: Napari-OmniEM
theme:
  name: mkdocs
  user_color_mode_toggle: true
nav:
  - Home: index.md
  - User Guide:
    - user-guide/index.md
    - Getting Started: user-guide/getting-started.md
    - Installation: user-guide/installation.md
    - In-memory Inference: user-guide/in-memory.md
    - Local Inference: user-guide/local.md
    - Parameters for Sliding Window: user-guide/sw.md
    - Task/solution Management: user-guide/manage.md
  - Model Zoo:
    - Overview: model-zoo/index.md
  - About:
    - More links: more.md
    - Release Notes: release-notes.md
    - License: license.md
  - GitHub: 'https://github.com/heliy/napari-omniem'
  - EM-SSL Project: 'https://github.com/pku-maleilab/EM-SSL-project'
